on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      versionOut: ${{ steps.generateVersion.outputs.version }}
    steps:
      - id: generateVersion
        run: echo "version=$(date '+%Y.%m.%d.%H%M%S').${{ github.run_number }}" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    container: golang:1.22-alpine
    steps:
      - uses: actions/checkout@v4
      - run: apk update && apk add --update curl openssl git openssh-client build-base
      - run: make build
  publish-balances:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: balances
      DOCKER_IMAGE_VERSION: ${{needs.version.outputs.versionOut}}
    needs:
      - version
    steps:
      - uses: docker/setup-buildx-action@v3
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: actions/checkout@v4
      - run: docker build -t ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${DOCKER_IMAGE_VERSION} -f images/${IMAGE_NAME}/Dockerfile .
      - run: docker push ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
