on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.22-alpine
    steps:
      - uses: actions/checkout@v4
      - run: apk update && apk add --update curl openssl git openssh-client build-base
      - run: make build
#  publish-balances:
#    runs-on: ubuntu-latest
#    env:
#      IMAGE_NAME: balances
#    steps:
#      - uses: docker/setup-buildx-action@v3
#      - uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ secrets.GITHUB_ACTOR }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - run: docker build -t ghcr.io/${{ github.repository }}/${IMAGE_NAME}:latest -f images/balances/Dockerfile .
#      - run: docker push ghcr.io/${{ github.repository }}/${IMAGE_NAME}:latest
