on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.21-alpine
    steps:
      - uses: actions/checkout@v4
      - run: apk update && apk add --update curl openssl git openssh-client build-base
      - run: make build